export const data = [
    {
        id: 1,
        firstName: 'Alice',
        lastName: 'Johnson',
        email: 'alice@gmail.com',
        city: 'Los Angeles',
        registeredDate: '2023-02-20',
        isPrivate: false,
    },
    {
        id: 2,
        firstName: 'John',
        lastName: 'Doe',
        email: 'john@gmail.com',
        city: 'New York',
        registeredDate: '2023-01-15',
        isPrivate: true,
    },
    {
        id: 3,
        firstName: 'Bob',
        lastName: 'Smith',
        email: 'bob@gmail.com',
        city: 'Chicago',
        registeredDate: '2023-03-25',
        isPrivate: true,
    },
    {
        id: 4,
        firstName: 'Emma',
        lastName: 'Wilson',
        email: 'emma@gmail.com',
        city: 'San Francisco',
        registeredDate: '2023-04-10',
        isPrivate: false,
    },
    {
        id: 5,
        firstName: 'Michael',
        lastName: 'Brown',
        email: 'michael@gmail.com',
        city: 'Houston',
        registeredDate: '2023-05-05',
        isPrivate: true,
    },
    {
        id: 6,
        firstName: 'Olivia',
        lastName: 'Lee',
        email: 'olivia@gmail.com',
        city: 'Miami',
        registeredDate: '2023-06-15',
        isPrivate: false,
    },
    {
        id: 7,
        firstName: 'William',
        lastName: 'Jones',
        email: 'william@gmail.com',
        city: 'Phoenix',
        registeredDate: '2023-07-20',
        isPrivate: true,
    },
    {
        id: 8,
        firstName: 'Sophia',
        lastName: 'Davis',
        email: 'sophia@gmail.com',
        city: 'Dallas',
        registeredDate: '2023-08-25',
        isPrivate: false,
    },
    {
        id: 9,
        firstName: 'James',
        lastName: 'Harris',
        email: 'james@gmail.com',
        city: 'Seattle',
        registeredDate: '2023-09-05',
        isPrivate: true,
    },
    {
        id: 10,
        firstName: 'Lily',
        lastName: 'Turner',
        email: 'lily@gmail.com',
        city: 'Boston',
        registeredDate: '2023-10-10',
        isPrivate: false,
    },
    // Add 10 more objects starting from the 11th object
    {
        id: 11,
        firstName: 'NewFirstName1',
        lastName: 'NewLastName1',
        email: 'new1@gmail.com',
        city: 'NewCity1',
        registeredDate: '2023-11-11',
        isPrivate: true,
    },
    {
        id: 12,
        firstName: 'NewFirstName2',
        lastName: 'NewLastName2',
        email: 'new2@gmail.com',
        city: 'NewCity2',
        registeredDate: '2023-12-12',
        isPrivate: false,
    },
    {
        id: 13,
        firstName: 'NewFirstName3',
        lastName: 'NewLastName3',
        email: 'new3@gmail.com',
        city: 'NewCity3',
        registeredDate: '2024-01-01',
        isPrivate: true,
    },
    {
        id: 14,
        firstName: 'NewFirstName4',
        lastName: 'NewLastName4',
        email: 'new4@gmail.com',
        city: 'NewCity4',
        registeredDate: '2024-02-02',
        isPrivate: false,
    },
    {
        id: 15,
        firstName: 'NewFirstName5',
        lastName: 'NewLastName5',
        email: 'new5@gmail.com',
        city: 'NewCity5',
        registeredDate: '2024-03-03',
        isPrivate: true,
    },
    {
        id: 16,
        firstName: 'NewFirstName6',
        lastName: 'NewLastName6',
        email: 'new6@gmail.com',
        city: 'NewCity6',
        registeredDate: '2024-04-04',
        isPrivate: false,
    },
    {
        id: 17,
        firstName: 'NewFirstName7',
        lastName: 'NewLastName7',
        email: 'new7@gmail.com',
        city: 'NewCity7',
        registeredDate: '2024-05-05',
        isPrivate: true,
    },
    {
        id: 18,
        firstName: 'NewFirstName8',
        lastName: 'NewLastName8',
        email: 'new8@gmail.com',
        city: 'NewCity8',
        registeredDate: '2024-06-06',
        isPrivate: false,
    },
    {
        id: 19,
        firstName: 'NewFirstName9',
        lastName: 'NewLastName9',
        email: 'new9@gmail.com',
        city: 'NewCity9',
        registeredDate: '2024-07-07',
        isPrivate: true,
    },
    {
        id: 20,
        firstName: 'NewFirstName10',
        lastName: 'NewLastName10',
        email: 'new10@gmail.com',
        city: 'NewCity10',
        registeredDate: '2024-08-08',
        isPrivate: false,
    },
    {
        id: 21,
        firstName: 'NewFirstName21',
        lastName: 'NewLastName21',
        email: 'new21@gmail.com',
        city: 'NewCity21',
        registeredDate: '2024-09-09',
        isPrivate: true,
    },
    {
        id: 22,
        firstName: 'NewFirstName22',
        lastName: 'NewLastName22',
        email: 'new22@gmail.com',
        city: 'NewCity22',
        registeredDate: '2024-10-10',
        isPrivate: false,
    },
    {
        id: 23,
        firstName: 'NewFirstName23',
        lastName: 'NewLastName23',
        email: 'new23@gmail.com',
        city: 'NewCity23',
        registeredDate: '2024-11-11',
        isPrivate: true,
    },
    {
        id: 24,
        firstName: 'NewFirstName24',
        lastName: 'NewLastName24',
        email: 'new24@gmail.com',
        city: 'NewCity24',
        registeredDate: '2024-12-12',
        isPrivate: false,
    },
    {
        id: 25,
        firstName: 'NewFirstName25',
        lastName: 'NewLastName25',
        email: 'new25@gmail.com',
        city: 'NewCity25',
        registeredDate: '2025-01-01',
        isPrivate: true,
    },
    {
        id: 26,
        firstName: 'NewFirstName26',
        lastName: 'NewLastName26',
        email: 'new26@gmail.com',
        city: 'NewCity26',
        registeredDate: '2025-02-02',
        isPrivate: false,
    },
    {
        id: 27,
        firstName: 'NewFirstName27',
        lastName: 'NewLastName27',
        email: 'new27@gmail.com',
        city: 'NewCity27',
        registeredDate: '2025-03-03',
        isPrivate: true,
    },
    {
        id: 28,
        firstName: 'NewFirstName28',
        lastName: 'NewLastName28',
        email: 'new28@gmail.com',
        city: 'NewCity28',
        registeredDate: '2025-04-04',
        isPrivate: false,
    },
    {
        id: 29,
        firstName: 'NewFirstName29',
        lastName: 'NewLastName29',
        email: 'new29@gmail.com',
        city: 'NewCity29',
        registeredDate: '2025-05-05',
        isPrivate: true,
    },
    {
        id: 30,
        firstName: 'NewFirstName30',
        lastName: 'NewLastName30',
        email: 'new30@gmail.com',
        city: 'NewCity30',
        registeredDate: '2025-06-06',
        isPrivate: false,
    },
    {
        id: 31,
        firstName: 'Ella',
        lastName: 'Miller',
        email: 'ella@gmail.com',
        city: 'Seattle',
        registeredDate: '2023-11-11',
        isPrivate: true,
    },
    {
        id: 32,
        firstName: 'Henry',
        lastName: 'Clark',
        email: 'henry@gmail.com',
        city: 'Chicago',
        registeredDate: '2023-12-12',
        isPrivate: false,
    },
    {
        id: 33,
        firstName: 'Grace',
        lastName: 'Martinez',
        email: 'grace@gmail.com',
        city: 'Los Angeles',
        registeredDate: '2024-01-01',
        isPrivate: true,
    },
    {
        id: 34,
        firstName: 'Aiden',
        lastName: 'Lewis',
        email: 'aiden@gmail.com',
        city: 'New York',
        registeredDate: '2024-02-02',
        isPrivate: false,
    },
    {
        id: 35,
        firstName: 'Sofia',
        lastName: 'Hernandez',
        email: 'sofia@gmail.com',
        city: 'Miami',
        registeredDate: '2024-03-03',
        isPrivate: true,
    },
    {
        id: 36,
        firstName: 'Ethan',
        lastName: 'Green',
        email: 'ethan@gmail.com',
        city: 'San Francisco',
        registeredDate: '2024-04-04',
        isPrivate: false,
    },
    {
        id: 37,
        firstName: 'Chloe',
        lastName: 'Parker',
        email: 'chloe@gmail.com',
        city: 'Dallas',
        registeredDate: '2024-05-05',
        isPrivate: true,
    },
    {
        id: 38,
        firstName: 'Liam',
        lastName: 'Adams',
        email: 'liam@gmail.com',
        city: 'Houston',
        registeredDate: '2024-06-06',
        isPrivate: false,
    },
    {
        id: 39,
        firstName: 'Lily',
        lastName: 'Turner',
        email: 'lily@gmail.com',
        city: 'Boston',
        registeredDate: '2024-07-07',
        isPrivate: true,
    },
    {
        id: 40,
        firstName: 'Mason',
        lastName: 'Wright',
        email: 'mason@gmail.com',
        city: 'Phoenix',
        registeredDate: '2024-08-08',
        isPrivate: false,
    },
    {
        id: 41,
        firstName: 'Ava',
        lastName: 'Gonzalez',
        email: 'ava@gmail.com',
        city: 'Los Angeles',
        registeredDate: '2024-09-09',
        isPrivate: true,
    },
    {
        id: 42,
        firstName: 'Noah',
        lastName: 'Carter',
        email: 'noah@gmail.com',
        city: 'New York',
        registeredDate: '2024-10-10',
        isPrivate: false,
    },
    {
        id: 43,
        firstName: 'Sophia',
        lastName: 'Perez',
        email: 'sophia@gmail.com',
        city: 'Chicago',
        registeredDate: '2024-11-11',
        isPrivate: true,
    },
    {
        id: 44,
        firstName: 'Liam',
        lastName: 'Evans',
        email: 'liam@gmail.com',
        city: 'San Francisco',
        registeredDate: '2024-12-12',
        isPrivate: false,
    },
    {
        id: 45,
        firstName: 'Olivia',
        lastName: 'Gray',
        email: 'olivia@gmail.com',
        city: 'Miami',
        registeredDate: '2025-01-01',
        isPrivate: true,
    },
    {
        id: 46,
        firstName: 'William',
        lastName: 'Stewart',
        email: 'william@gmail.com',
        city: 'Phoenix',
        registeredDate: '2025-02-02',
        isPrivate: false,
    },
    {
        id: 47,
        firstName: 'Amelia',
        lastName: 'Morris',
        email: 'amelia@gmail.com',
        city: 'Dallas',
        registeredDate: '2025-03-03',
        isPrivate: true,
    },
    {
        id: 48,
        firstName: 'James',
        lastName: 'Jenkins',
        email: 'james@gmail.com',
        city: 'Seattle',
        registeredDate: '2025-04-04',
        isPrivate: false,
    },
    {
        id: 49,
        firstName: 'Evelyn',
        lastName: 'Ward',
        email: 'evelyn@gmail.com',
        city: 'Houston',
        registeredDate: '2025-05-05',
        isPrivate: true,
    },
    {
        id: 50,
        firstName: 'Logan',
        lastName: 'Cook',
        email: 'logan@gmail.com',
        city: 'Boston',
        registeredDate: '2025-06-06',
        isPrivate: false,
    },
    {
        id: 51,
        firstName: 'Elijah',
        lastName: 'Collins',
        email: 'elijah@gmail.com',
        city: 'Los Angeles',
        registeredDate: '2025-07-07',
        isPrivate: true,
    },
    {
        id: 52,
        firstName: 'Mia',
        lastName: 'Bennett',
        email: 'mia@gmail.com',
        city: 'New York',
        registeredDate: '2025-08-08',
        isPrivate: false,
    },
    {
        id: 53,
        firstName: 'Grayson',
        lastName: 'Parker',
        email: 'grayson@gmail.com',
        city: 'Chicago',
        registeredDate: '2025-09-09',
        isPrivate: true,
    },
    {
        id: 54,
        firstName: 'Aria',
        lastName: 'Carter',
        email: 'aria@gmail.com',
        city: 'San Francisco',
        registeredDate: '2025-10-10',
        isPrivate: false,
    },
    {
        id: 55,
        firstName: 'Ethan',
        lastName: 'Butler',
        email: 'ethan@gmail.com',
        city: 'Miami',
        registeredDate: '2025-11-11',
        isPrivate: true,
    },
    {
        id: 56,
        firstName: 'Scarlett',
        lastName: 'Foster',
        email: 'scarlett@gmail.com',
        city: 'Phoenix',
        registeredDate: '2025-12-12',
        isPrivate: false,
    },
    {
        id: 57,
        firstName: 'Mason',
        lastName: 'Gray',
        email: 'mason@gmail.com',
        city: 'Dallas',
        registeredDate: '2026-01-01',
        isPrivate: true,
    },
    {
        id: 58,
        firstName: 'Luna',
        lastName: 'Hayes',
        email: 'luna@gmail.com',
        city: 'Seattle',
        registeredDate: '2026-02-02',
        isPrivate: false,
    },
    {
        id: 59,
        firstName: 'Carter',
        lastName: 'Adams',
        email: 'carter@gmail.com',
        city: 'Houston',
        registeredDate: '2026-03-03',
        isPrivate: true,
    },
    {
        id: 60,
        firstName: 'Aurora',
        lastName: 'Ward',
        email: 'aurora@gmail.com',
        city: 'Boston',
        registeredDate: '2026-04-04',
        isPrivate: false,
    },
    {
        id: 61,
        firstName: 'Liam',
        lastName: 'Collins',
        email: 'liam@gmail.com',
        city: 'Los Angeles',
        registeredDate: '2026-05-05',
        isPrivate: true,
    },
    {
        id: 62,
        firstName: 'Olivia',
        lastName: 'Bennett',
        email: 'olivia@gmail.com',
        city: 'New York',
        registeredDate: '2026-06-06',
        isPrivate: false,
    },
    {
        id: 63,
        firstName: 'Noah',
        lastName: 'Parker',
        email: 'noah@gmail.com',
        city: 'Chicago',
        registeredDate: '2026-07-07',
        isPrivate: true,
    },
    {
        id: 64,
        firstName: 'Emma',
        lastName: 'Carter',
        email: 'emma@gmail.com',
        city: 'San Francisco',
        registeredDate: '2026-08-08',
        isPrivate: false,
    },
    {
        id: 65,
        firstName: 'Liam',
        lastName: 'Butler',
        email: 'liam@gmail.com',
        city: 'Miami',
        registeredDate: '2026-09-09',
        isPrivate: true,
    },
    {
        id: 66,
        firstName: 'Ava',
        lastName: 'Foster',
        email: 'ava@gmail.com',
        city: 'Phoenix',
        registeredDate: '2026-10-10',
        isPrivate: false,
    },
    {
        id: 67,
        firstName: 'Elijah',
        lastName: 'Gray',
        email: 'elijah@gmail.com',
        city: 'Dallas',
        registeredDate: '2026-11-11',
        isPrivate: true,
    },
    {
        id: 68,
        firstName: 'Mia',
        lastName: 'Hayes',
        email: 'mia@gmail.com',
        city: 'Seattle',
        registeredDate: '2026-12-12',
        isPrivate: false,
    },
    {
        id: 69,
        firstName: 'Evelyn',
        lastName: 'Adams',
        email: 'evelyn@gmail.com',
        city: 'Houston',
        registeredDate: '2027-01-01',
        isPrivate: true,
    },
    {
        id: 70,
        firstName: 'Logan',
        lastName: 'Ward',
        email: 'logan@gmail.com',
        city: 'Boston',
        registeredDate: '2027-02-02',
        isPrivate: false,
    },
    {
        id: 71,
        firstName: 'Aiden',
        lastName: 'Collins',
        email: 'aiden@gmail.com',
        city: 'Los Angeles',
        registeredDate: '2027-03-03',
        isPrivate: true,
    },
    {
        id: 72,
        firstName: 'Chloe',
        lastName: 'Bennett',
        email: 'chloe@gmail.com',
        city: 'New York',
        registeredDate: '2027-04-04',
        isPrivate: false,
    },
    {
        id: 73,
        firstName: 'Evelyn',
        lastName: 'Parker',
        email: 'evelyn@gmail.com',
        city: 'Chicago',
        registeredDate: '2027-05-05',
        isPrivate: true,
    },
    {
        id: 74,
        firstName: 'Ethan',
        lastName: 'Carter',
        email: 'ethan@gmail.com',
        city: 'San Francisco',
        registeredDate: '2027-06-06',
        isPrivate: false,
    },
    {
        id: 75,
        firstName: 'Olivia',
        lastName: 'Butler',
        email: 'olivia@gmail.com',
        city: 'Miami',
        registeredDate: '2027-07-07',
        isPrivate: true,
    },
    {
        id: 76,
        firstName: 'William',
        lastName: 'Foster',
        email: 'william@gmail.com',
        city: 'Phoenix',
        registeredDate: '2027-08-08',
        isPrivate: false,
    },
    {
        id: 77,
        firstName: 'Mason',
        lastName: 'Gray',
        email: 'mason@gmail.com',
        city: 'Dallas',
        registeredDate: '2027-09-09',
        isPrivate: true,
    },
    {
        id: 78,
        firstName: 'Luna',
        lastName: 'Hayes',
        email: 'luna@gmail.com',
        city: 'Seattle',
        registeredDate: '2027-10-10',
        isPrivate: false,
    },
    {
        id: 79,
        firstName: 'Carter',
        lastName: 'Adams',
        email: 'carter@gmail.com',
        city: 'Houston',
        registeredDate: '2027-11-11',
        isPrivate: true,
    },
    {
        id: 80,
        firstName: 'Aurora',
        lastName: 'Ward',
        email: 'aurora@gmail.com',
        city: 'Boston',
        registeredDate: '2027-12-12',
        isPrivate: false,
    },
    {
        id: 81,
        firstName: 'Elijah',
        lastName: 'Collins',
        email: 'elijah@gmail.com',
        city: 'Los Angeles',
        registeredDate: '2028-01-01',
        isPrivate: true,
    },
    {
        id: 82,
        firstName: 'Mia',
        lastName: 'Bennett',
        email: 'mia@gmail.com',
        city: 'New York',
        registeredDate: '2028-02-02',
        isPrivate: false,
    },
    {
        id: 83,
        firstName: 'Noah',
        lastName: 'Parker',
        email: 'noah@gmail.com',
        city: 'Chicago',
        registeredDate: '2028-03-03',
        isPrivate: true,
    },
    {
        id: 84,
        firstName: 'Emma',
        lastName: 'Carter',
        email: 'emma@gmail.com',
        city: 'San Francisco',
        registeredDate: '2028-04-04',
        isPrivate: false,
    },
    {
        id: 85,
        firstName: 'Liam',
        lastName: 'Butler',
        email: 'liam@gmail.com',
        city: 'Miami',
        registeredDate: '2028-05-05',
        isPrivate: true,
    },
    {
        id: 86,
        firstName: 'Ava',
        lastName: 'Foster',
        email: 'ava@gmail.com',
        city: 'Phoenix',
        registeredDate: '2028-06-06',
        isPrivate: false,
    },
    {
        id: 87,
        firstName: 'Elijah',
        lastName: 'Gray',
        email: 'elijah@gmail.com',
        city: 'Dallas',
        registeredDate: '2028-07-07',
        isPrivate: true,
    },
    {
        id: 88,
        firstName: 'Mia',
        lastName: 'Hayes',
        email: 'mia@gmail.com',
        city: 'Seattle',
        registeredDate: '2028-08-08',
        isPrivate: false,
    },
    {
        id: 89,
        firstName: 'Evelyn',
        lastName: 'Adams',
        email: 'evelyn@gmail.com',
        city: 'Houston',
        registeredDate: '2028-09-09',
        isPrivate: true,
    },
    {
        id: 90,
        firstName: 'Logan',
        lastName: 'Ward',
        email: 'logan@gmail.com',
        city: 'Boston',
        registeredDate: '2028-10-10',
        isPrivate: false,
    },
    {
        id: 91,
        firstName: 'Liam',
        lastName: 'Collins',
        email: 'liam@gmail.com',
        city: 'Los Angeles',
        registeredDate: '2028-11-11',
        isPrivate: true,
    },
    {
        id: 92,
        firstName: 'Olivia',
        lastName: 'Bennett',
        email: 'olivia@gmail.com',
        city: 'New York',
        registeredDate: '2028-12-12',
        isPrivate: false,
    },
    {
        id: 93,
        firstName: 'Noah',
        lastName: 'Parker',
        email: 'noah@gmail.com',
        city: 'Chicago',
        registeredDate: '2029-01-01',
        isPrivate: true,
    },
    {
        id: 94,
        firstName: 'Emma',
        lastName: 'Carter',
        email: 'emma@gmail.com',
        city: 'San Francisco',
        registeredDate: '2029-02-02',
        isPrivate: false,
    },
    {
        id: 95,
        firstName: 'Liam',
        lastName: 'Butler',
        email: 'liam@gmail.com',
        city: 'Miami',
        registeredDate: '2029-03-03',
        isPrivate: true,
    },
    {
        id: 96,
        firstName: 'Ava',
        lastName: 'Foster',
        email: 'ava@gmail.com',
        city: 'Phoenix',
        registeredDate: '2029-04-04',
        isPrivate: false,
    },
    {
        id: 97,
        firstName: 'Elijah',
        lastName: 'Gray',
        email: 'elijah@gmail.com',
        city: 'Dallas',
        registeredDate: '2029-05-05',
        isPrivate: true,
    },
    {
        id: 98,
        firstName: 'Mia',
        lastName: 'Hayes',
        email: 'mia@gmail.com',
        city: 'Seattle',
        registeredDate: '2029-06-06',
        isPrivate: false,
    },
    {
        id: 99,
        firstName: 'Evelyn',
        lastName: 'Adams',
        email: 'evelyn@gmail.com',
        city: 'Houston',
        registeredDate: '2029-07-07',
        isPrivate: true,
    },
    {
        id: 100,
        firstName: 'Logan',
        lastName: 'Ward',
        email: 'logan@gmail.com',
        city: 'Boston',
        registeredDate: '2029-08-08',
        isPrivate: false,
    },
]